name: 'Test action'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

permissions:
  contents: read 
  
jobs:
  test:
    if: ${{ !contains(github.event.pull_request.title, '[cov]') }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Git credentials
        run: |
          git config --global url."https://${{ secrets.REPO_ACCESS_TOKEN }}:x-oauth-basic@github.com/FairgateLabs/".insteadOf "https://github.com/FairgateLabs/"

      - name: Checkout rust-bitvmx-workspace
        uses: actions/checkout@v4
        with:
          repository: FairgateLabs/rust-bitvmx-workspace
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: main
          path: rust-bitvmx-workspace # Store in $GITHUB_WORKSPACE/other-repo
          submodules: true
      
      - name: Build project
        run: |
          cd rust-bitvmx-workspace/rust-bitvmx-protocol-builder
          cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
  
  test-with-coverage:
    if: ${{ contains(github.event.pull_request.title, '[cov]') }}
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
    - name: Set up Git credentials
      run: |
        git config --global url."https://${{ secrets.REPO_ACCESS_TOKEN }}:x-oauth-basic@github.com/FairgateLabs/".insteadOf "https://github.com/FairgateLabs/"

    - name: Checkout rust-bitvmx-workspace
      uses: actions/checkout@v4
      with:
        repository: FairgateLabs/rust-bitvmx-workspace
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        ref: main
        path: rust-bitvmx-workspace # Store in $GITHUB_WORKSPACE/other-repo
        submodules: true

    - name: Run cargo-tarpaulin
      uses: actions-rs/tarpaulin@v0.1
      with:
        version: '0.15.0'
        args: '--out Xml --output-dir resources --exclude-files src/tests/* config/* src/main.rs rust-bitcoin-script/* rust-bitcoin-scriptexec/* rust-bitvmx-key-manager/* --no-fail-fast'

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: resources/cobertura.xml
        badge: true
        format: markdown
        output: both
    
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        ignore_empty: true
        recreate: true        
        path: code-coverage-results.md  
